name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version your project needs

      - name: Install dependencies
        run: npm install

      - name: Install Vite globally
        run: npm install -g vite

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: YOUR_FIREBASE_PROJECT_ID
